name: Base image

on:
  workflow_dispatch:

jobs:
  build_bases:
    name: Build base image
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: [win64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create and Boot docker-container Driver
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Image Name
        id: imagename
        run: |
          IMG="ghcr.io/${GITHUB_ACTOR,,}/base-${{ matrix.target }}"
          echo "image=${IMG/ /-}:latest" >> $GITHUB_OUTPUT
          echo "cache=${IMG/ /-}:cache" >> $GITHUB_OUTPUT

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: images/base-${{ matrix.target }}
          outputs: type=registry,oci-mediatypes=true,compression=zstd,compression-level=7
          cache-from: type=registry,ref=${{ steps.imagename.outputs.cache }}
          cache-to: type=registry,ref=${{ steps.imagename.outputs.cache }},mode=max,oci-mediatypes=true,compression=zstd,compression-level=7
          tags: ${{ steps.imagename.outputs.image }}
          provenance: false

